server:
  port: 8888

spring:
  cloud:
    config:
      label: master
      nane: web-config
      profile: dev
      server:
        git:
          uri: https://github.com/zkpking/springcloud.git
          search-paths: config-repo
          password: zkpking@gmail.com
          username: XXXXXX
