server:
  port: 8888

spring:
  application:
    name: springcloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zkpking/springcloudconfig.git
          search-paths: config-repo
          password: zkpking@gmail.com
          username: kaider317012784
  boot:
    admin:
      client:
        url: http://localhost:8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
